# Default application configuration that all configurations inherit from.
# https://github.com/brigade/scss-lint

scss_files: '**/*.scss'

# exclude: 'src/_client/lib/whatever/**'

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: false
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: tab # or 'space'
    width: 1

  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 6

  PlaceholderInExtend:
    enabled: true

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'fr',                                    # Grid
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%',                                     # Other
    ]
    properties: {}

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    # BASED ON: SMACSS Property Order
    # SEE: https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/smacss.txt
    # AND: http://smacss.com/book/formatting
    # AND: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertysortorder
    order: [
      # Box
      'content', 'float', 'clear', 'overflow', 'overflow-x', 'overflow-y',
      'display', 'table-layout',
      'grid-template-columns', 'grid-template-rows', 'grid-template-areas', 'grid-template',
      'grid-auto-columns', 'grid-auto-rows', 'grid-auto-flow', 'grid',
      'grid-row-start', 'grid-column-start', 'grid-row-end', 'grid-column-end',
      'grid-row', 'grid-column', 'grid-area', 'grid-row-gap', 'grid-column-gap', 'grid-gap',
      'flex-direction', 'flex-wrap', 'justify-content', 'align-content', 'align-items',
      'flex', 'flex-grow', 'flex-shrink', 'flex-basis', 'order',
      'position', 'top', 'right', 'bottom', 'left',
      'width', 'min-width', 'max-width',
      'height', 'min-height', 'max-height',
      'margin', 'margin-top', 'margin-right', 'margin-bottom', 'margin-left',
      'padding', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left',
      'columns', 'column-gap', 'column-fill', 'column-rule', 'column-span', 'column-count', 'column-width',
      # Background
      'background', 'background-color', 'background-image', 'background-repeat', 'background-position', 'background-size',
      # Border
      'outline', 'outline-color', 'outline-offset', 'outline-style', 'outline-width',
      'border', 'border-top', 'border-right', 'border-bottom', 'border-left', 'border-width', 'border-top-width', 'border-right-width', 'border-bottom-width', 'border-left-width',
      'border-style', 'border-top-style', 'border-right-style', 'border-bottom-style', 'border-left-style',
      'border-radius', 'border-top-left-radius', 'border-top-right-radius', 'border-bottom-left-radius', 'border-bottom-right-radius',
      'border-color', 'border-top-color', 'border-right-color', 'border-bottom-color', 'border-left-color',
      'box-shadow',
      # Text
      'color',
      'font', 'font-family', 'font-size', 'font-smoothing', 'font-style', 'font-variant', 'font-weight',
      'list-style', 'letter-spacing', 'line-height',
      'text-align', 'text-decoration', 'text-indent', 'text-overflow', 'text-rendering', 'text-shadow', 'text-transform', 'text-wrap',
      'white-space', 'word-spacing',
      # Animation and Manipulation
      'transform', 'transition', 'opacity',
      # Cursor
      'cursor', 'pointer-events', 'user-select',
      # Other
      'border-collapse', 'border-spacing', 'caption-side', 'empty-cells', 'quotes', 'speak', 'vertical-align', 'visibility', 'z-index',
    ]
    separate_groups: false

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: false
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 8

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAroundOperator:
    enabled: false
    style: one_space # or 'at_least_one_space' or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: false
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false

  PseudoElement:
    enabled: false
