type User {
	username: String!
	email: String
	bio: String
	avatar: String
	displayName: String
	first: String
	last: String
	posts: [Post]
}

extend type Query {
	user(username: String!): User
	users: [User]
}
